Some improvements
Koenkk/zigbee2mqtt pull request #50
Opened 2018-05-17 07:54 UTC by ptvoinfo

Added polling for routers (prevents deep sleep mode of Xiaomi routers)
Added more parsers for Xiaomi Power Plug
Added a custom router

2018-05-17 16:35 UTC, Koenkk commented on lib/converters/zigbee2mqtt.js
> +                    temperature: precisionRound(data['3'], 2), // ??
`consumption` and `temperature` seems to report strange values: `'{"power":3.65,"state":"ON","voltage":234,"consumption":0.02,"temperature":47}'`. This is with a Sonos one speaker connected, temperature definitely isn't 47 degrees and I don't know what consumption means.

2018-05-17 16:39 UTC, Koenkk requested changes

2018-05-17 16:39 UTC, Koenkk commented on lib/controller.js
> +          if ((dt - this.lastControllerActivity) > 3600000) {
I feel it's better to use a event (like a usb disconnect) instead of a timeout. Also, isn't there any event triggered from zigbee-shepherd when an error with a connection to the CC2531 happens?

2018-05-18 04:00 UTC, ptvoinfo commented on lib/controller.js
> +          if ((dt - this.lastControllerActivity) > 3600000) {
In my home application CC2531 just freezes rarely (once in 1 or 2 weeks). It think CC2531 may reset/reboot internally but zigbee-shepherd does catch this event. Then CC2531 stays uninitialized and does not work properly.

2018-05-18 04:03 UTC, ptvoinfo commented on lib/converters/zigbee2mqtt.js
> +                    temperature: precisionRound(data['3'], 2), // ??
temperature - I think this is the temperature of the interval sensor (overheat protection). consumption - power consumption measured from last state OFF => ON. power - power consumption from a last power on of the plug.

2018-05-21 10:01 UTC, Koenkk approved these changes

2018-05-21 10:03 UTC, Koenkk commented
Thanks!

2018-05-21 10:03 UTC, merged