Add default on all HA templates for attributes
Koenkk/zigbee2mqtt pull request #6988
Opened 2021-04-07 15:35 UTC by mdegat01

Implemented the fix I suggested in #6987 . I blindly added the `| default('', true)` syntax to every template as I do not know the ins and outs of all these situations. If some discovery payloads should not have this added because they should always be reporting in that state let me know which and I will update.

Can also change the mechanism for defaulting or the value if desired. As I said in the issue, I picked `''` because that is what used to happen prior to `2021.4.0`. But now that we have control over the default, can switch it to `None` if that's preferred.

2021-04-07 15:38 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +                    value_template: `{% if 'update' in value_json %}{{ value_json['update']['state'] }}{% endif %}`,
This is the only one that breaks the pattern. It looks for a field within a field so either field could generate this error. I figured if `update` exists then `state` exists within it and used this check instead. Let me know if we need to separately check for the existence of `state` within `update` or if this check should just be removed (like if `update_state` is always reported by the devices which support it)

2021-04-07 15:48 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +                                ` %}{{ values[value_json.${state.property}] }}{% endif %}`;
Upon further review, this one also has to break the mold. Took another look and realized what it was doing, adding a default on `value_json.property` isn't enough here since `values` doesn't have a key of `''`. So adjusted this template to also include a surrounding if check and not do anything if the state its looking for isn't in the payload.

2021-04-08 12:38 UTC, frenck requested changes
I could ask the same thing on each change in this PR...: Why would that value be missing?

This feels like a temporary workaround solution. And we all now temporarily solutions are permanent.

2021-04-08 12:38 UTC, frenck commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
This is defeating the whole purpose of the change from Home Assistant.

2021-04-08 12:38 UTC, frenck commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
Why would the click be missing?

2021-04-08 12:38 UTC, frenck commented on lib/extension/homeassistant.js
> +                        value_template: `{{ value_json.brightness ${safeDefault} }}`,
Why would brightness be missing?

2021-04-08 14:25 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
Your points are fair, I don't disagree. I unfortunately do not know the answer to which attributes should be provided with every payload (and thus shouldn't be defaulted) and which are only provided occaisionally (and thus should). I said as much in the PR description:

> If some discovery payloads should not have this added because they should always be reporting in that state let me know which and I will update.

I'm not an expert here, I have to rely on Koenkk for that. What I saw was that beta was about to become stable and the large number of Z2M users were very likely to see a mass of unexplainable warnings like this:

```
Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'
```

These users did not configure this template, they didn't construct the discovery payload, in fact its very likely they didn't even know templates were involved in Zigbee2MQTT until this moment as it is completely UI-configured. I imagine a lot of users would have a difficult time even making the connection between that warning and Zigbee2MQTT since it doesn't say anything about Z2M or MQTT. They would just be frustrated and confused by the stream of warnings.

The point of this PR was really just to help get ahead of this and hopefully avoid frustrated users crashing on HA and this repo. I know it probably needs some adjustment but at least it highlights every spot where a template is used to hopefully make it easier to figure out which need a default and which shouldn't have that added.

But I can change the variable name, that's fair. I was actually mentally connecting `safe` with `''` since it was recreating the current behavior, hence 'safe'. But you're right, its a weird name.

2021-04-08 14:28 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
So this one I believe is actually one we do want to default. Looking at the warnings users are putting on the issue (as well as my experience locally with my own Zigbee devices) the primary source of this warning is going to be from action events on devices. It seems like the devices only report a message with an action event when an action is taken and Z2M only reports that kind of state when it gets a message with an action event.

Based on the name `click` this seems like one of those kinds of attributes that really would need a default. But I'll have to let Koenkk weigh in as I don't have any devices which report `click`, only `action`.

2021-04-08 14:32 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +                        value_template: `{{ value_json.brightness ${safeDefault} }}`,
Completely fair, perhaps this template should not be changed. Locally the only time I was able to recreate a situation where I was receiving messages from a device that reports `brightness` without that attribute was when I used `filtered_attributes`. But in those cases I should be disabling the corresponding HA sensor so I personally don't consider that valid justification for this default.

That being said, there are 1400+ different supported devices and I have about 10 available for testing. I don't know if there are other devices out there which create messages with only some of the fields. I'll need an SME to weigh in there.

2021-04-08 14:34 UTC, McGiverGim commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
It's difficult to know what must be sent when the value is missing. Some sensors sent some of the values from time to time, and this is causing this problem. 

Sending it empty like this PR will remove the warning in HA, but I'm not too sure if this can have some additional effect. What does HA when it receives a blank? It ignores it or replaces the latest "correct" value by a blank?

Another solution is to send the latest known value in Z2M, but maybe this is not the correct value, for example a `low battery` maybe is not right if we have miss some update while off, but it will be the "same" value than HA contains, except if we go back with some snapshot in HA or Z2M.

2021-04-08 14:38 UTC, derekoharrow commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
I've seen this in action and the reason a click might be missing is because devices can send status updates at times other than when a click/action occurs. For example, a Xiaomi Aqara button will send a battery level update every so often, and that doesn't include the click.
Similarly, I get lots of messages that don't always include linkquality, which is another source of the errors.

2021-04-08 14:39 UTC, frenck commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
Users are important, but I'm not sure how the whole user story applies here. This is a PR that is incorrect IMHO and you don't disagree.

There is nothing broken and no rush (6 months!). So I suggest this if fixed in a proper manner.

The default should ideally be handled in the payload, not in the template handling.

2021-04-08 14:42 UTC, frenck commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
I think it tries to publish a "clear" message for the click?

A `''` (empty string) is still a state. Though. The solution here relies in still publishing a `click`, either as a null value (resulting in an `Unknown` state in Home Assistant), or, actually make it a state like `Idle`. Whatever the case, the `click` attribute should be there.

2021-04-08 14:43 UTC, frenck commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
> It's difficult to know what must be sent when the value is missing. Some sensors sent some of the values from time to time, and this is causing this problem.

Even if that is the case, the payload should reflect that "unknown" / missing state consistently.

2021-04-08 14:44 UTC, derekoharrow commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
Nope, here's a recent example I captured, with no click and no linkquality:

`{“battery”:86,“last_seen”:“2021-04-08T14:02:40+01:00”,“voltage”:2975}`

2021-04-08 14:46 UTC, frenck commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
> Similarly, I get lots of messages that don't always include linkquality, which is another source of the errors.

Those are cases that should still report the linkquality attribute, with e.g., a null value, or else there is no way to tell the different between a missing value or missing attribute.

2021-04-08 14:46 UTC, derekoharrow commented on lib/extension/homeassistant.js
> +        value_template: `{{ value_json.click ${safeDefault} }}`,
p.s. I'm using "legacy: false" in my configuration.yaml for z2m, as per recommendations, which means that it no longer publishes "click" events and should publish "action" events instead - but as you can see in that example, that's missing too...

2021-04-08 16:18 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
> Sending it empty like this PR will remove the warning in HA, but I'm not too sure if this can have some additional effect. What does HA when it receives a blank? It ignores it or replaces the latest "correct" value by a blank?

Just an FYI, I used `''` as the default because that's what happens today. Any time HA received a message from Z2M with one or more expected attributes missing it was setting the state of the corresponding sensor to `''`. That's why I picked that value, the idea was to put out a PR which mimics the behavior we have today.

Of course this is Frenck's point here, we should question whether we want the behavior we have today. It's been silently using `''` for a long time, the only thing that changed is that now users can see that's happening.

I really don't know the answer to that. My gut impression is that attributes like `action` should get a default as their not really states. If you have a device like a remote that provides action you can see that it the corresponding `action` sensor switches to the action value based on what was pressed then nearly instantaneously switches back to not having a state. Its really an event not a state. One could probably argue that now that Z2M creates devices and device triggers the sensor shouldn't exist at all. I know I personally have the sensor disabled in my HA, I don't need it.

For the others that are actually states I see Frenck's point, defaulting in the template might be the wrong approach. If changing how the payloads are made is the correct approach then this PR should probably just close. I can take a look but I'm not sure I'm comfortable wading that far into Z2M to see where the payloads are made. I know HA pretty well but for Z2M I really only know how it interacts with HA. I'm not sure how the rest of it works and am limited in my abilities to test other types of deployments.

2021-04-08 16:21 UTC, frenck commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
> Just an FYI, I used '' as the default because that's what happens today. 

Is being removed. Adding it back again makes no sense.

2021-04-08 18:02 UTC, mdegat01 commented
Converting this to draft since there's a lot to unpack in this discussion here. Also `2021.4.0` is out and there doesn't seem to be as many instances of this issue as I was worried there would be so probably good to step back.

Digesting all this I feel like maybe the approach should be like this:

1. Remove the `default` test from most of the templates. To the points above things like `brightness`, `linkquality`, etc. should always be coming in so `default` just hides errors.
2. Identify the few that are really events not state like `action` and thus are only reported occaisionally. For those I think special handling is required, something along these lines:
  - Deprecate them in favor of device triggers. Z2M already sets these up so you can trigger an automation from an action from your zigbee device. That is the preferred way to do device actions in HA today. Since they are deprecated its fine that a warning is logged (preferrable actually). Although hopefully there's some way to log a message which says what is wrong like "using `sensor.<device>_action` is deprecated, use a device trigger instead".
  - If there is a way to log that better message then adjust the template to include `| default('', true)`. We don't want to spam the log with template warnings to hide the real deprecation warning.
  - Stop making those sensors for new devices. In a predefined deprecation timeline (maybe the same 6 months?) stop sending the action as a state of the device.
   
Thoughts?

2021-04-08 18:55 UTC, Koenkk commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
@frenck to confirm, would all of this be solved if Z2M fills the unknown values with `null`? e.g. `{"temperature": null, "humidity": null}`?

2021-04-08 19:24 UTC, McGiverGim commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
It would change the state in Home Assistant to unknown. I don't think this is the correct solution for attributes that are sent sometimes. I suppose Z2M must sent the latest known value, and if unknown or very old, discard it and sent null.

2021-04-08 19:38 UTC, frenck commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
> @frenck to confirm, would all of this be solved if Z2M fills the unknown values with null

Depends if the value is unknown or not applicable. The null/None value in Home Assistant = currently unknown.

>  I suppose Z2M must sent the latest known value

That is assuming a state I presume?

2021-04-08 20:07 UTC, frenck commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
For the **state attributes**, that would be correct. They always need to be provided as a set as a whole (this is the case for Home Assistant integrations as well).

That said, state attributes in general, should be avoided as it is often actually an entity by itself. To be fair, integrations that do this, will not pass code-review nowadays @ Home Assistant.

Individual states of entities, can be updated though, its combining things that should not be combined that becomes problematic.

-> Back to the change at hand.

Defaulting to an empty string (as the old behavior was), **didn't actually do a partial update either**. This emphasizes the change Home Assistant is doing here, as in the previous case, the state would also have updated to an empty string 😉  (because not a partial update).

2021-04-08 20:40 UTC, derekoharrow commented
I can see how that would work for actions, but I'm curious how this would work with for attributes that you might be interested in capturing - e.g. linkquality.

2021-04-08 22:10 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
When I said `attributes` there I think I caused confusion. I wasn't thinking of HA attributes, I was thinking of the device's attributes. When I connect a new device to Z2M it creates a new device in HA and creates `n` sensors based on the expected state that device will provide (ex. for my T/H sensor I get a sensor each for `temperature`, `humidity`, `pressure`, `linkquality`, `battery_level`, and `voltage`). What I'm trying to figure out is two things:

a) Are there devices which have a list of aspects/attributes like that which only update some of them with each message they send out?
b) Is there a way to provide an MQTT message to HA which only updates some of the sensors created from the original MQTT discovery message?

2021-04-08 22:15 UTC, mdegat01 commented on lib/extension/homeassistant.js
> +const safeDefault = `| default('', true)`;
Ah I see. You'd have to break them up. Looking at the discovery messages right now, there's one per sensor but they all listen to the same state topic. That's the real problem here, that makes it impossible to update just one.

2021-04-09 07:23 UTC, McGiverGim commented
If it helps, I've three different cases:
- Xiaomi relay (LLKZMK11LM). It has an `interlock` attribute that by default is `false`, but is not published by the updates of the device. So Z2M does not show the value for this device. When you change it explicitly to `true` or `false` then Z2M starts reporting the value.
- Xiaomi vibration (DJT11LM) and Xiaomi wireless switch (WXKG01LM). It has an `action` that is published in a different message than the standard state of the device. As said, maybe is fixed migrating to HA triggers.
- Xiaomi water leak (SJCGQ11LM). It has a `low_battery` and `tamper` attributes that are `unknown`. I have never seen this attributes with values, so maybe is a bug in Z2M and this attributes must be removed?

2021-04-09 08:25 UTC, derekoharrow commented
I'm not sure how moving to Device Triggers would actually help. Z2M would still use home assistant discovery, which means the other devices would still be created, which means the error would still occur (it's not using them as a trigger that's the issue, it's Z2M posting status messages that HA doesn't like that is).

If you were to take that approach, then you'd need to suppress the posting of HA discovery messages so that the device isn't picked-up and created by HA, but then you wouldn't be able to retrieve the values like link quality or battery, etc. (Other then perhaps when a click type event occurs).

I've thought of one alternative that could work. In z2m you can already specify device specific values to override homeassistant discovery configuration. Why not add an option in here to override the value for the topic, which then gives the users the ability to include the default value if they wish to for their specific use case.

That way, the overall behaviour of Z2M is retained, but can be overridden by choice for those people with problematic devices.

2021-04-09 21:31 UTC, mdegat01 commented
> If you were to take that approach, then you'd need to suppress the posting of HA discovery messages so that the device isn't picked-up and created by HA, but then you wouldn't be able to retrieve the values like link quality or battery, etc. (Other then perhaps when a click type event occurs).

In HA, open up the configuration page for one of the devices created by Z2M and click "MQTT Info". You can see all the different discovery messages Z2M posted for the device, there's an individual discovery message for each of the following:

1. The device itself
2. The individual entities for attributes of the device (`linkquality`, `battery`, `temperature`, etc.)
3. The device triggers/actions which should be created for that device to be used in scripts and automations

I didn't realize it was so individual at first either. Once I looked at that's when I realized the `action` entity is really just redundant in the current environment. You can simply not publish discovery for that and only publish the device trigger discovery messages. Nothing else would be affected, you'd still have `linkquality`, `battery`, etc. and all the actual state entities of the device. You just wouldn't have a sensor for `action`, only a device trigger.

> I've thought of one alternative that could work. In z2m you can already specify device specific values to override homeassistant discovery configuration. Why not add an option in here to override the value for the topic, which then gives the users the ability to include the default value if they wish to for their specific use case.

That could work. Its very manual though. If this is new normal I feel like it should work without warnings or errors by default and not require additional configuration. Still it is an option.

2021-04-10 18:33 UTC, Koenkk commented
Created an alternative fix for this here: https://github.com/Koenkk/zigbee2mqtt/pull/7032

2021-04-12 15:28 UTC, mdegat01 commented
Closing this as #7032  fixes this properly

2021-04-12 15:28 UTC, closed without merging